import Head from "next/head"

export default function Home() {
  const handleButtonClick = () => {
    console.log("do nothing")
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>next app</h1>
        <button onClick={handleButtonClick}>just button</button>
      </main>
    </>
  )
}
